### ISSUE TITLE
Uninstallation Issue

### ISSUE THREAD

**Issue by WHYGAMEJOLTWHY** [Dual-Iron/RwModLoader#10]
When I uninstalled it took my BepInEx folder with it, and all my mods. >:(

I'm not sure if it was a bug but I assume it is.

**Comment by kuvithanol** [comment]
realm will always consume the contents of your bepinex folder, that is part of its design

**Comment by Dual-Iron** [comment]
Uninstalling an app typically means erasing it and its data from your computer, yeah. That's by design.

If you want to keep the mods, just delete `BepInEx\patchers\Realm.dll`. The files will remain in `BepInEx\realm` for whenever you may use BepInEx or Realm.
