### ISSUE TITLE
BepInEx fails to initialize under Proton with Realm installed.

### ISSUE THREAD

**Issue by neomoth** [Dual-Iron/RwModLoader#13]
**Describe the bug**
BepInEx fails to initialize properly with realm installed on Linux (Running Rain World under Steam Proton), preventing Rain World from even launching fully.

**To Reproduce**
- Install BepInEx and Realm on Linux
- Edit the BepInEx config settings to output logs to a terminal
- Launch Rain World under Proton after putting `WINEDLLOVERRIDES="winhttp=n,b" %command%` in the launch options to make BepInEx actually run.
- Observe terminal output and see that the game never fully launches.

**Expected behavior**
The game should launch with BepInEx and Realm loaded.

**Screenshots**
- BepInEx log: (it stops after this error with Realm installed)
![image](https://user-images.githubusercontent.com/69372252/159095452-2987c62f-52cb-4608-8c5f-bf6bd0ff9584.png)

**Additional context**
Linux distro being used is Arch Linux with kernel version 5.10.88-2-lts
Game will launch with BepInEx if Realm either is not installed or the Realm folder is missing in the BepInEx folder.

**Comment by Dual-Iron** [comment]
Delete your `BepInEx` folder then reinstall Realm. The Dragons patchers should be removed after Realm is installed (fixed in ffbe2534d7ae8d582168f4b31375412f296c97c1). Ty for your report!

**Comment by neomoth** [comment]
Realm works now, however the game does not seem to be properly loading mods. If i start the game with mods in the plugins folder, the game never opens, and if i put the mods in after starting the game and refreshing the mod list, it seems to load indefinitely and all menu buttons stay grayed out, effectively softlocking me in the menu. And yes I have made sure to update Realm, this happens on the new version too.

**Comment by neomoth** [comment]
The game also seems to lock up like this when attempting to download a mod from the browser. Files seem to be appearing when trying to load mods or download them in the Realm folder though, but it doesn't go any further than that. (example: putting ConfigMachine.dll in BepInEx/plugins makes ConfigMachine.rwmod or something of that sort appear in BepInEx/realm/mods, and downloading RideableLizards from the browser results in RideableLizards.rwmod to appear in BepInEx/realm/mods, and a temp folder to appear in BepInEx/realm.) I assume this is correct behavior, but it seems to lock up and stop working almost immediately.

**Comment by Dual-Iron** [comment]
Does it work with no mods installed? How about just ConfigMachine?

Also, could you open the game with no mods in the plugins folder, then reload in the mod menu, and send your logs?

**Comment by neomoth** [comment]
It works with zero mods installed, as there is nothing for it to load, and no having just config machine also makes it not start the game (or if i start the game, add it, and refresh mods, it loads indefinitely)
The only thing output to console when refreshing is:
```
[Info   :     Realm] Loading mods
```
There are no errors in the log or anything its just that.

**Comment by Dual-Iron** [comment]
Alright. Could you:
1. Install [this](https://github.com/Dual-Iron/RwModLoader/suites/6140439937/artifacts/214199613) version
2. Launch with no files in the `BepInEx/plugins` or `BepInEx/realm/mods` folders
3. Add ConfgMachine to the `plugins` folder and reload your mods, let it freeze
4. Close RW and send `BepInEx/LogOutput.log` to me again

The log "Loading mods" is sent just before multithreading is used. Is it possible your system doesn't allow `ThreadPool.QueueUserWorkItem` or Unity multi-threading in general?

I apologize for the delayed response.

**Comment by Dual-Iron** [comment]
It may help if you check out the Rain World Discord server. I'm more active and we can communicate rapidly.

Find me on https://discord.gg/rainworld under the name `@dual curly potato noodles#2355`

**Comment by Dual-Iron** [comment]
PJB made a guide that should be applicable to Realm on Proton: https://gist.github.com/PJB3005/a7b635f171bd34f18a28885afa8f6e8e
