### ISSUE TITLE
"Please reinstall Realm" on linux

### ISSUE THREAD

**Issue by u1f98e** [Dual-Iron/RwModLoader#9]
**Describe the bug**
Installed Realm on a fresh game install, using the same wineprefix as the game. Results in the above message on the title screen.  The log gives a fatal error:
`[Fatal  :     Realm] Mutator not present. Please reinstall Realm!`
[Full log here](https://github.com/Dual-Iron/RwModLoader/files/7836094/LogOutput.log)
Should probably also mention reinstalling doesn't work.

**Additional context**
Running on Proton 6.3-8, also tried the most recent 7.0rc3 of GloriousEggroll's proton.

**Comment by Dual-Iron** [comment]
I suspect that Realm is misbehaving on your operating system when it looks for an %appdata% folder. The error is raised [here](https://github.com/Dual-Iron/RwModLoader/blob/39afc82982a5fed21f22b768ece12d4080e081a1/Realm/Program.cs#L33).

I have an idea of how I may fix this, but it may take some time.

To help me debug, can you replace the `Rain World/BepInEx/patchers/Realm.dll` file with the below file, run the game, then send your new logs? The file itself is a test build that will print some important info and then abort before loading any mods. You can inspect it with dnSpy if you don't trust me.

https://cdn.discordapp.com/attachments/412054141947609089/933238710567313418/Realm.dll

Thanks!

**Comment by u1f98e** [comment]
[Here's the new log](https://github.com/Dual-Iron/RwModLoader/files/7901260/LogOutput.log)
No more error on the main menu, but also no other menu buttons, which I assume is because of the debug mode. It does look like it's having an issue with Appdata, all I can see is that a .rw folder gets created there on game launch but nothing else.

**Comment by Dual-Iron** [comment]
Here's a build that moves all data from `%appdata%/.rw` to `Rain World/BepInEx/realm`.

Uninstall your current Realm instance by deleting the `Rain World/BepInEx` folder and running the file below. Let me know if it works for you. Thanks again.

https://github.com/Dual-Iron/RwModLoader/actions/runs/1731940398

**Comment by u1f98e** [comment]
That's fixed it!
